# Generated by Django 4.0 on 2021-12-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='follower_id',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='following_id',
        ),
    ]
