name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python manage.py test network.tests.UserTestCase
        python manage.py test network.tests.FollowerTestCase
        python manage.py test network.tests.LikesTestCase
        python manage.py test network.tests.PostTestCase